image: waxteam/dev:v1.6.1

before_script:
  # Install ssh-agent if not already installed, it is required by Docker.
  # (change apt-get to yum if you use a CentOS-based image)
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'

  # Run ssh-agent (inside the build environment)
  - eval $(ssh-agent -s)

  # Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
  - ssh-add <(echo "$SSH_PRIVATE_KEY")

  # Add the mcmxi gitlab pub key to known_hosts
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo "$MCMXI_SERVER_HOSTKEY" > ~/.ssh/known_hosts'

  ## clone the project each time (inefficient, consider performing fetch instead if it already exists)
  - git clone ssh://git@monica.mcmxi.services:2259/wax/$CI_PROJECT_NAME.git $CLONE_DIR
  - cd ./$CI_PROJECT_NAME
  - git reset --hard $CI_COMMIT_SHA

stages:
  - test

tests:
  stage: test
  script:
    - make test
  tags:
    - docker
